version: '3.7'

services:

#######################################################################################################
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
#######################################################################################################
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - 'GF_ALERTING_ENABLED=false' #disable dashboard alerting
      - 'GF_UNIFIED_ALERTING_ENABLED=true' #enable alerting independent from dashboards

    ports:
      - 3000:3000
    networks:
      - monitoring
#######################################################################################################
  mysql_container:
    image: mysql:8.0.33
    container_name: mysql_container
    networks:
      - spring_app-mysql_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : yes
      MYSQL_DATABASE: Mydatabase

    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
#######################################################################################################
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_container
    networks:
      - spring_app-mysql_network
    links:
      - mysql_container
    environment:
      PMA_HOST: mysql_container
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8082:80"
#######################################################################################################
  spring-boot-container: 
    networks:
      - spring_app-mysql_network
    image: spring-boot-image
    container_name: spring-boot-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql_container
    environment:
      - spring.datasource.url =jdbc:mysql://mysql_container:3306/Mydatabase?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
#######################################################################################################

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
#######################################################################################################
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    networks:
      - monitoring
###################################################################################################
networks:
  spring_app-mysql_network:   

      
